# Generated by Django 4.2.8 on 2023-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('all', models.DecimalField(decimal_places=2, max_digits=3)),
                ('most', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sometimes', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rarely', models.DecimalField(decimal_places=2, max_digits=3)),
                ('never', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
