# Generated by Django 4.2.8 on 2024-02-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
